name: speech_recognition
description: A flutter plugin to use the speech recognition on iOS and Android
version: 0.3.0
author: Erick Ghaumez <erick@rxla.bz>
homepage: https://github.com/rxlabz/speech_recognition

flutter:
  plugin:
    androidPackage: bz.rxla.flutter.speechrecognition
    pluginClass: SpeechRecognitionPlugin

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^3.0.0

environment:
  sdk: '>=2.0.0-dev.49.0 <3.0.0'
